version: '3.9'

services:
  db:
    image: postgres:14
    container_name: isolocate_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: isolocate_user
      POSTGRES_PASSWORD: isolocate_pass
      POSTGRES_DB: isolocate_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:latest
    depends_on:
      - db
    volumes:
      - ./migrations:/flyway/sql
      - ./flyway.conf:/flyway/conf/flyway.conf
    command: -configFiles=/flyway/conf/flyway.conf -locations=filesystem:/flyway/sql -connectRetries=60 migrate

  app:
    build:
      context: ./app
      dockerfile: ../Dockerfile
    container_name: isolocate_app
    depends_on:
      - db
      - flyway
    environment:
      - DATABASE_URL=postgresql://isolocate_user:isolocate_pass@db:5432/isolocate_db
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    container_name: isolocate_worker
    depends_on:
      - db
      - flyway
    environment:
      - DATABASE_URL=postgresql://isolocate_user:isolocate_pass@db:5432/isolocate_db
    volumes:
      - ./worker:/worker
      - ./reference-datasets:/reference-datasets
